import React from 'react';
import { GeneratedImage } from '../types';

interface PreviewProps {
  image: GeneratedImage | null;
  isGenerating: boolean;
}

export const Preview: React.FC<PreviewProps> = ({ image, isGenerating }) => {
  const handleDownload = () => {
    if (!image) return;
    const link = document.createElement('a');
    link.href = image.url;
    link.download = `thumbnail-${image.timestamp}.png`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (!image && !isGenerating) {
    return (
      <div className="h-full min-h-[400px] flex flex-col items-center justify-center bg-slate-800/30 rounded-2xl border-2 border-dashed border-slate-700 p-8 text-center">
        <div className="w-16 h-16 bg-slate-800 rounded-full flex items-center justify-center mb-4">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-8 h-8 text-slate-500">
            <path strokeLinecap="round" strokeLinejoin="round" d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
          </svg>
        </div>
        <h3 className="text-xl font-medium text-slate-300 mb-2">Ready to Create</h3>
        <p className="text-slate-500 max-w-xs">
          Enter your podcast details and select a style to generate unique cover art.
        </p>
      </div>
    );
  }

  return (
    <div className="relative group rounded-2xl overflow-hidden shadow-2xl bg-black">
      {isGenerating && (
        <div className="absolute inset-0 z-10 flex items-center justify-center bg-black/70 backdrop-blur-sm">
          <div className="flex flex-col items-center gap-4">
             <div className="relative w-20 h-20">
                <div className="absolute inset-0 rounded-full border-4 border-slate-700"></div>
                <div className="absolute inset-0 rounded-full border-4 border-indigo-500 border-t-transparent animate-spin"></div>
             </div>
             <p className="text-indigo-200 font-medium animate-pulse">AI is painting...</p>
          </div>
        </div>
      )}
      
      {image && (
        <>
          <img
            src={image.url}
            alt={image.prompt}
            className={`w-full h-auto object-contain max-h-[600px] transition-opacity duration-500 ${isGenerating ? 'opacity-50' : 'opacity-100'}`}
          />
          <div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black/90 via-black/50 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end justify-between">
            <div className="text-white">
                <p className="text-xs font-mono text-indigo-300 mb-1">Generated by Gemini</p>
            </div>
            <button
              onClick={handleDownload}
              className="bg-white text-black px-4 py-2 rounded-lg font-bold text-sm hover:bg-indigo-50 transition-colors flex items-center gap-2"
            >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-4 h-4">
                <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
              </svg>
              Download
            </button>
          </div>
        </>
      )}
    </div>
  );
};